name: sky-jump-app # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Sky Jump Fantasy Quest
summary: Leap through magical floating islands.
description: Explore mythical skies by jumping across enchanted platforms to reach your heroic destiny.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  sky-jump-app:
    command: bin/sky-jump-app-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  sky-jump-app:
    plugin: dump
    source: .
    organize:
      sky-jump-app-bin: bin/
